package org.jcmgb.veganizer.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@lombok.Data
@DynamoDBTable(tableName = "recipes")
public class Recipe {
    private String id;
    private String title;
    private String ingredients;
    private String steps;
    private String veganized;
    private int count;

    public Recipe() {
    }

    public Recipe(String title, String ingredients, String steps) {
        this.title = title;
        this.ingredients = ingredients;
        this.steps = steps;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    @DynamoDBAttribute
    public String getTitle() {
        return title;
    }

    @DynamoDBAttribute
    public String getIngredients() {
        return ingredients;
    }

    @DynamoDBAttribute
    public String getSteps() {
        return steps;
    }

    @DynamoDBAttribute
    public String getVeganized() {
        return veganized;
    }

    @DynamoDBAttribute
    public int getCount() {
        return count;
    }


    public void setId(String id) {
        this.id = id;
    }
    public void setTitle(String title) {
        this.title = title;
    }
    public void setIngredients(String ingredients) {
        this.ingredients = ingredients;
    }
    public void setSteps(String steps) {
        this.steps = steps;
    }
    public void setVeganized(String veganized) {
        this.veganized = veganized;
    }
    public void setCount(int count) {
        this.count = count;
    }
}
