package org.jcmgb.veganizer.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "substitutions")
public class Substitution {
    private String id;
    private String ingredient1;
    private String ingredient2;
    private String vegansub;
    private String category;
    private String notes;

    public Substitution() {
    }

    public Substitution(String title, String ingredient2, String vegansub, String notes, String category) {
        this.ingredient1 = title;
        this.ingredient2 = ingredient2;
        this.vegansub = vegansub;
        this.notes = notes;
        this.category = category;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    @DynamoDBAttribute
    public String getIngredient1() {
        return ingredient1;
    }

    @DynamoDBAttribute
    public String getIngredient2() {
        return ingredient2;
    }

    @DynamoDBAttribute
    public String getVegansub() {
        return vegansub;
    }

    @DynamoDBAttribute
    public String getCategory() {
        return category;
    }

    @DynamoDBAttribute
    public String getNotes() {
        return notes;
    }

    public void setId(String id) {
        this.id = id;
    }
    public void setIngredient1(String ingredient1) {
        this.ingredient1 = ingredient1;
    }
    public void setIngredient2(String ingredient2) {
        this.ingredient2 = ingredient2;
    }
    public void setVegansub(String vegansub) {
        this.vegansub = vegansub;
    }
    public void setCategory(String category) { this.category = category; }
    public void setNotes(String notes) {
        this.notes = notes;
    }
}
